version: '3.8'

services:

  mongodb:
    container_name: mongodb_for_scripts
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
